name: CI
on: [push, pull_request]

jobs:
  build:
    name: Test Listener Middleware on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install deps
        run: yarn install

        # The middleware apparently needs RTK built first for tests to compile (?!?)
      - name: Build RTK
        run: cd packages/toolkit && yarn build

      - name: Run action listener tests
        run: cd packages/action-listener-middleware && yarn test
